
services:
  rabbitmq:
    container_name: localhost_rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - custom


  db:
    image: postgres:13-alpine
    volumes:
        - pg_data:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - custom


  redis:
    image: redis:latest
    container_name: redis_container
    
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - custom


  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
        - web
    ports:
        - "80:80"
    volumes:
        - ./nginx-conf.d:/etc/nginx/conf.d
    
    networks:
      - custom


  web:
    build: .
    working_dir: /app/bot
    command: uvicorn main:app --host 0.0.0.0 --port 8000

    volumes:
      - ./bot:/app/bot

    environment:
        - ADMIN_IDS=${ADMIN_IDS}
        - BOT_TOKEN=${BOT_TOKEN}
        - DB_URL=${DB_URL}
        - STORE_URL=${STORE_URL}
        - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
        - RABBITMQ_URL=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
        - TZ=Europe/Moscow

    depends_on:
        - db
        - redis
        - rabbitmq
    networks:
      - custom


  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: start --all --config /etc/ngrok.yml
    
    ports:
      - "4040:4040" # Панель управления ngrok
    depends_on:
      - web
    networks:
      - custom

 
networks:
  custom:
    driver: bridge

volumes:
  pg_data:
  redisdata: