"""Initial revision

Revision ID: 99b4892c415c
Revises: 385b61921b4a
Create Date: 2025-04-12 23:13:02.185824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b4892c415c'
down_revision: Union[str, None] = '385b61921b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
